// Generated by CoffeeScript 1.3.3
(function() {

  window.nameinput = {
    maxlength: 35,
    lettersonly: true,
    regex: /^[a-zA-Z ]+$/,
    notblank: true
  };

  window.emailinput = {
    malength: 35,
    regex: /^\w+@[a-zA-Z_]+?\.[a-zA-Z]{2,3}$/
  };

  window.isblank = function(str) {
    if (str.length === 0) {
      return true;
    } else {
      return false;
    }
  };

  window.tooLong = function(string, maxlength) {
    if (string.length <= maxlength) {
      return false;
    } else {
      return true;
    }
  };

  window.tooShort = function(string, minlength) {
    if (string.length >= minlength) {
      return false;
    } else {
      return true;
    }
  };

  window.validateText = function(text, min, max) {
    var increment, totalitems, validitems;
    validitems = 0;
    totalitems = 4;
    if (min == null) {
      min = 3;
    }
    if (max == null) {
      max = 35;
    }
    increment = function() {
      return validitems++;
    };
    if (!isblank(text)) {
      increment();
    }
    if (!tooShort(text, min)) {
      increment();
    }
    if (!tooLong(text, max)) {
      increment();
    }
    if (nameinput.regex.test(text)) {
      increment();
    }
    if (validitems < totalitems) {
      return false;
    } else {
      return true;
    }
  };

  window.validateEmail = function(email) {
    var increment, totalitems, validitems;
    validitems = 0;
    totalitems = 1;
    increment = function() {
      return validitems++;
    };
    if (emailinput.regex.test(email)) {
      increment();
    }
    if (validitems < totalitems) {
      return false;
    } else {
      return true;
    }
  };

  window.isPhone = function(input) {
    var regex;
    regex = /^\(?([0-9]{3})\)?[-. ]?([0-9]{3})\s*[-. ]?\s*([0-9]{4})$/;
    return regex.test(input);
  };

  window.is_int = function(value) {
    if (parseFloat(value) === parseInt(value) && !isNaN(value)) {
      return true;
    } else {
      return false;
    }
  };

  $(function() {
    var form, input;
    window.valid = false;
    form = $('#form');
    input = '#form > .step input';
    ($(input + '[type=text],' + input + '[type=password],' + input + '[type=email]')).change(function() {
      if (($(this)).attr('optional') !== "yes") {
        if (validateText($(this).val(), $(this).attr('min'), $(this).attr('max'))) {
          return $(this).removeClass('error').addClass('success').attr('valid', 'true');
        } else {
          return $(this).removeClass('success').addClass('error').attr('valid', 'false');
        }
      }
    });
    ($(input + '.phone')).change(function() {
      if (isPhone($(this).val())) {
        return $(this).removeClass('error').addClass('success').attr('valid', 'true');
      } else {
        return $(this).removeClass('success').addClass('error').attr('valid', 'false');
      }
    });
    ($(input + '.email')).change(function() {
      if (validateEmail($(this).val())) {
        $(this).removeClass('error').addClass('success').attr('valid', 'true');
      } else {
        $(this).removeClass('success').addClass('error').attr('valid', 'false');
      }
      if ($(this).val() != null) {
        return $(this).addClass('success');
      } else {
        return $(this).addClass('error');
      }
    });
    ($(input + '[type=radio]')).change(function() {
      var name;
      name = $(this).attr('name');
      if ($('input[name=' + name + ']').is(':checked')) {
        return $('.error-text.radio').remove();
      } else {
        return $('input[name=' + name + ']').first().before('<p class="error-text radio">Select an option!</p>');
      }
    });
    ($(input + '[type=checkbox]')).change(function(e) {
      var max, min;
      min = 1;
      max = 9999;
      if ($('input[name=' + $(this).prop('name') + ']').first().attr('min') != null) {
        min = $('input[name=' + $(this).prop('name') + ']').first().attr('min').match(/\d+/);
      }
      if ($('input[name=' + $(this).prop('name') + ']').first().attr('max') != null) {
        max = $('input[name=' + $(this).prop('name') + ']').first().attr('max').match(/\d+/);
      }
      if ($('input[name=' + $(this).prop('name') + ']').is(':checked') && $('input[name=checks]:checked').length <= max && $('input[name=checks]:checked').length >= min) {
        return $('.error-text.checkbox').remove();
      } else {
        $('.error-text.checkbox').remove();
        return $('input[name=' + $(this).prop('name') + ']').first().before('<p class="error-text checkbox">Select at least ' + min + ' boxes!</p>');
      }
    });
    ($('#form > .step select')).change(function() {
      if (($(this).val() != null) && ($(this)).val() !== '') {
        return $(this).removeClass('error');
      } else {
        return $(this).addClass('error');
      }
    });
    return $('#form > .step .submit').click(function(e) {
      var thisStep;
      thisStep = $(this).parent();
      e.preventDefault();
      window.totalitems = 0;
      window.validitems = 0;
      thisStep.children(input + '[type=text],' + input + '[type=password],' + input + '[type=email]').each(function() {
        window.totalitems++;
        if ($(this).attr('valid') === 'true' || ($(this)).attr('optional') === "yes") {
          window.validitems++;
        } else {
          $(this).removeClass('success').addClass('error').focus();
          false;
        }
        return console.log(validitems, totalitems);
      });
      thisStep.children('select').each(function() {
        window.totalitems++;
        if (($(this).val() != null) && $(this).val() !== "") {
          window.validitems++;
          return $(this).removeClass('error');
        } else {
          return $(this).addClass('error');
        }
      });
      thisStep.children('input[type=radio]').each(function() {
        var name;
        name = $(this).attr('name');
        window.totalitems++;
        if ($('input[name=' + name + ']').is(':checked')) {
          window.validitems++;
        } else {
          $('.error-text.radio').remove();
          $('input[name=' + name + ']').first().before('<p class="error-text radio">Select an option!</p>');
        }
        return console.log(validitems, totalitems);
      });
      thisStep.children('input[type=checkbox]').each(function() {
        var max, min, name;
        window.totalitems++;
        min = 1;
        max = 9999;
        if ($('input[name=' + $(this).prop('name') + ']').first().attr('min') != null) {
          min = $('input[name=' + $(this).prop('name') + ']').first().attr('min').match(/\d+/);
        }
        if ($('input[name=' + $(this).prop('name') + ']').first().attr('max') != null) {
          max = $('input[name=' + $(this).prop('name') + ']').first().attr('max').match(/\d+/);
        }
        name = $(this).attr('name');
        if ($('input[name=' + $(this).prop('name') + ']').is(':checked') && $('input[name=checks]:checked').length <= max && $('input[name=checks]:checked').length >= min) {
          $('.error-text.checkbox').remove();
          window.validitems++;
        } else {
          $('.error-text.checkbox').remove();
          $('input[name=' + $(this).prop('name') + ']').first().before('<p class="error-text checkbox">Select at least ' + min + ' boxes!</p>');
        }
        return console.log(validitems, totalitems);
      });
      if (window.totalitems === window.validitems) {
        if (thisStep.attr('id') !== "last-step") {
          thisStep.slideUp();
          return thisStep.next('.step').slideDown();
        } else {
          return ($('#form')).submit();
        }
      }
    });
  });

}).call(this);
